apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-deployment
  type: LoadBalancer
  ports:
    - port: 8002
      targetPort: 8080
      protocol: TCP


